version: '3.4'

services:

  api:
    image: api
    build:
      context: ./..
      dockerfile: docker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Internal
      - ASPNETCORE_URLS=http://+:5000
    command:
      - /bin/sh
      - -c
      - |
          echo "Sleep workaround to wait for SQL Server"
          sleep 15
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      sqlserver:
        condition: service_healthy